<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="LANG">
<context>
    <name>ctkModalityWidget</name>
    <message>
        <source>CR</source>
        <translation>CR</translation>
    </message>
    <message>
        <source>CT</source>
        <translation>CT</translation>
    </message>
    <message>
        <source>MR</source>
        <translation>MR</translation>
    </message>
    <message>
        <source>NM</source>
        <translation>NM</translation>
    </message>
    <message>
        <source>US</source>
        <translation>US</translation>
    </message>
    <message>
        <source>OT</source>
        <translation>OT</translation>
    </message>
    <message>
        <source>BI</source>
        <translation>BI</translation>
    </message>
    <message>
        <source>CD</source>
        <translation>CD</translation>
    </message>
    <message>
        <source>DD</source>
        <translation>DD</translation>
    </message>
    <message>
        <source>DG</source>
        <translation>DG</translation>
    </message>
    <message>
        <source>ES</source>
        <translation>ES</translation>
    </message>
    <message>
        <source>LS</source>
        <translation>LS</translation>
    </message>
    <message>
        <source>PT</source>
        <translation>PT</translation>
    </message>
    <message>
        <source>RG</source>
        <translation>RG</translation>
    </message>
    <message>
        <source>ST</source>
        <translation>ST</translation>
    </message>
    <message>
        <source>TG</source>
        <translation>TG</translation>
    </message>
    <message>
        <source>XA</source>
        <translation>XA</translation>
    </message>
    <message>
        <source>RF</source>
        <translation>RF</translation>
    </message>
    <message>
        <source>RTIMAGE</source>
        <translation>RTIMAGE</translation>
    </message>
    <message>
        <source>RTDOSE</source>
        <translation>RTDOSE</translation>
    </message>
    <message>
        <source>RTSTRUCT</source>
        <translation>RTSTRUCT</translation>
    </message>
    <message>
        <source>RTPLAN</source>
        <translation>RTPLAN</translation>
    </message>
    <message>
        <source>RTRECTORD</source>
        <translation>RTRECTORD</translation>
    </message>
    <message>
        <source>HC</source>
        <translation>HC</translation>
    </message>
    <message>
        <source>DX</source>
        <translation>DX</translation>
    </message>
    <message>
        <source>MG</source>
        <translation>MG</translation>
    </message>
    <message>
        <source>IO</source>
        <translation>IO</translation>
    </message>
    <message>
        <source>PX</source>
        <translation>PX</translation>
    </message>
    <message>
        <source>GM</source>
        <translation>GM</translation>
    </message>
    <message>
        <source>SM</source>
        <translation>SM</translation>
    </message>
    <message>
        <source>XC</source>
        <translation>XC</translation>
    </message>
    <message>
        <source>PR</source>
        <translation>PR</translation>
    </message>
    <message>
        <source>AU</source>
        <translation>AU</translation>
    </message>
    <message>
        <source>ECG</source>
        <translation>ECG</translation>
    </message>
    <message>
        <source>EPS</source>
        <translation>EPS</translation>
    </message>
    <message>
        <source>HD</source>
        <translation>HD</translation>
    </message>
    <message>
        <source>SR</source>
        <translation>SR</translation>
    </message>
    <message>
        <source>IVUS</source>
        <translation>IVUS</translation>
    </message>
    <message>
        <source>OP</source>
        <translation>OP</translation>
    </message>
    <message>
        <source>SMR</source>
        <translation>SMR</translation>
    </message>
    <message>
        <source>OCT</source>
        <translation>OCT</translation>
    </message>
    <message>
        <source>OPR</source>
        <translation>OPR</translation>
    </message>
    <message>
        <source>OPV</source>
        <translation>OPV</translation>
    </message>
    <message>
        <source>OPM</source>
        <translation>OPM</translation>
    </message>
    <message>
        <source>KO</source>
        <translation>KO</translation>
    </message>
    <message>
        <source>SEG</source>
        <translation>SEG</translation>
    </message>
    <message>
        <source>REG</source>
        <translation>REG</translation>
    </message>
</context>
</TS>
